services:
  - type: web
    name: matchlink
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: MATCHLINK_ADMIN
        value: Yizney
      - key: MATCHLINK_CACHE_DIR
        value: /tmp/matchlink
      - key: MATCHLINK_DOMAIN
        sync: false
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /api/info
    plan: free